### ISSUE TITLE
Hard limit on the title size?

### ISSUE THREAD

**Issue by bblodfon** [biohackrxiv/submission-templates#1]
Hi,

I noticed that by using the [submission template example](https://github.com/biohackrxiv/submission-templates) and using a large enough title (I believe the hard limit is 70 characters), the output pdf is not generated and results in a latex error. I believe that having such a (low?) hard limit might not be for the best.

E.g. try using: `title: 'BioHackrXiv template mpla mpla mpla mpla mpla mpla mpla mpla mpla mpla mpla'`) in the example and you should be able to reproduce it (I use the docker).

PS: I would post this in the `bhxiv-gen-pdf` repo, but I couldn't make an issue there.

**Comment by inutano** [comment]
Thanks for trying @bblodfon! I've tried with the Docker version (described [here](https://github.com/biohackrxiv/bhxiv-gen-pdf#run-via-docker)) and it produces the PDF with the title longer than 70 chars. This may be because of the installation setup. Could you try with the container?

**Comment by bblodfon** [comment]
@inutano it works! Though I couldn't run the docker actually have some issue with `citeproc` there, but using `./bin/gen-pdf` worked nicely.
