### ISSUE TITLE
Support for svg images

### ISSUE THREAD

**Issue by bblodfon** [biohackrxiv/submission-templates#2]
Hi! 

Using the current dockerized version of [bhxiv-gen-pdf](https://github.com/biohackrxiv/bhxiv-gen-pdf) and specifying an `.svg` image in a `paper.md` file, results in a Latex error:
```
[WARNING] Could not convert image './tex2pdf.-24b668cd91501cba/a5ae2ca17c24d7ba5ab7505f4bb7d011744cda4a.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Unknown graphics extension: .svg.
```

This feature would be nice to have since it would enable high quality graphic images in the papers.

**Comment by inutano** [comment]
Added `rsvg2pdf` to Dockerfile. Could you try and let me know if it fixed the problem here? https://github.com/biohackrxiv/bhxiv-gen-pdf/tree/add-rsvg2
